language: python
python:
  - '3.6'
 
addons:
  firefox: latest

branches:
  only:
    - staging

before_script:
  - install-webdrivers
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="PureBeurre.settings.travis"

services:
  - postgresql

script:
  - cd PureBeurre && python manage.py test -v2
