language: python
python:
  - '3.6'
 
addons:
  firefox: latest
  sauce_connect:
    username: "GeoffreyRe"
    access_key: "6023c745-aab3-496f-877a-b981d8a51f67"

branches:
  only:
    - staging

before_script:
  - install-webdrivers
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="PureBeurre.settings.travis"
    - SECRET_KEY="auubcdjqbcekdqedz1561ef450e"
services:
  - postgresql

script:
  - cd PureBeurre && python manage.py test -v2
